CREATE TABLE "PLAYER" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "SCORE" INTEGER NOT NULL
);

CREATE TABLE "MATCH" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "PLAYER_ID" INTEGER NOT NULL,
    "SCORE" INTEGER NOT NULL,
    "DATE" TEXT NOT NULL,
    FOREIGN KEY("PLAYER_ID") REFERENCES "PLAYER"("ID")
);

CREATE TABLE "STATS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "PLAYER_ID" INTEGER NOT NULL,
    "MATCHES" INTEGER NOT NULL,
    "WINS" INTEGER NOT NULL,
    "LOSSES" INTEGER NOT NULL,
    "WIN_RATE" REAL NOT NULL,
    FOREIGN KEY("PLAYER_ID") REFERENCES "PLAYER"("ID")
);


-- Path: database/insert.sql
