CREATE TABLE "PLAYER" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "NAME" TEXT NOT NULL,
    "MMR" INTEGER NOT NULL
);

CREATE TABLE "MATCH" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "PLAYER_ID" INTEGER NOT NULL,
    "WINNING_TEAM" TEXT NOT NULL,
    "GAME_DURATION" INTEGER NOT NULL,
    "DATE" TEXT NOT NULL,
    FOREIGN KEY("PLAYER_ID") REFERENCES "PLAYER"("ID")
);

CREATE TABLE "PLAYERSTATS" (
    "ID" INTEGER PRIMARY KEY AUTOINCREMENT,
    "PLAYER_ID" INTEGER NOT NULL,
    "MATCHES" INTEGER NOT NULL,
    "WINS" INTEGER NOT NULL,
    "LOSSES" INTEGER NOT NULL,
    "WIN_RATE" REAL NOT NULL,
    FOREIGN KEY("PLAYER_ID") REFERENCES "PLAYER"("ID")
);


CREATE TABLE "PLAYERMATCHSTATS" (
    --Player data in json data interface for refrence
    "MATCH_ID" INTEGER NOT NULL,
    "PLAYER_ID" INTEGER NOT NULL,
    "TEAM_ID" INTEGER NOT NULL,
    "HERO_ID" INTEGER NOT NULL,
    "ROLE" TEXT NOT NULL,

    "LANE_MINIONS_KILLED" INTEGER NOT NULL,
    "NEUTRAL_MINIONS_KILLED" INTEGER NOT NULL,
    "NEUTRAL_MINIONS_KILLED_TEAM_JUNGLE" INTEGER NOT NULL,
    "NEUTRAL_MINIONS_KILLED_ENEMY_JUNGLE" INTEGER NOT NULL,

    "KILLS" INTEGER NOT NULL,
    "DEATHS" INTEGER NOT NULL,
    "ASSISTS" INTEGER NOT NULL,
    "LARGEST_KILLING_SPREE" INTEGER NOT NULL,
    "LARGEST_MULTI_KILL" INTEGER NOT NULL,

    "TOTAL_DAMAGE_DEALT" INTEGER NOT NULL,
    "PHYSICAL_DAMAGE_DEALT" INTEGER NOT NULL,
    "MAGIC_DAMAGE_DEALT" INTEGER NOT NULL,
    "TRUE_DAMAGE_DEALT" INTEGER NOT NULL,
    "LARGEST_CRITICAL_STRIKE" INTEGER NOT NULL,
    "TOTAL_DAMAGE_DEALT_TO_CHAMPIONS" INTEGER NOT NULL,


    "DAMAGE" INTEGER NOT NULL,
    "GOLD" INTEGER NOT NULL,

    FOREIGN KEY("MATCH_ID") REFERENCES "MATCH"("ID"),
    FOREIGN KEY("PLAYER_ID") REFERENCES "PLAYER"("ID")

)

CREATE TABLE "PLAYEROVERALLSTATS" (

)

-- Path: database/insert.sql
